import Link from "next/link";
import Image from "@/app/korean-skin-treatments/shared/GuideImage";
import ArticleFeedback from "../ArticleFeedback";
import { getArticleMetadata, getArticleJsonLd } from "../article";
import CardCarousel from "../CardCarousel";

export const metadata = getArticleMetadata(true);

export default function UpsellCardsPage() {
  return <div className="skin-guide cards-body">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(getArticleJsonLd(true)).replace(/</g, "\u003c") }} />
    <Link prefetch={false} className="skip" href="#card-track">카드 본문 바로가기</Link><header className="relyn-header"><div className="relyn-header-inner"><Link prefetch={false} className="relyn-brand" href="/" aria-label="RELYN 홈"><Image src="/relyn_logo.png" sizes="(max-width: 600px) 100px, 128px" loading="eager" width="1024" height="358" alt="RELYN" /></Link><span className="brand-divider" aria-hidden="true"></span><Link prefetch={false} className="guide-label" href="/korean-skin-treatments/upsell-kr">가이드</Link><nav className="view-switch" aria-label="읽는 방식"><Link prefetch={false} href="/korean-skin-treatments/upsell-kr">글로 읽기</Link><Link prefetch={false} href="/korean-skin-treatments/upsell-kr/cards" aria-current="page">카드로 보기</Link></nav></div></header><nav className="breadcrumb" aria-label="현재 위치"><Link prefetch={false} href="/">RELYN 홈</Link><span aria-hidden="true">/</span><Link prefetch={false} className="breadcrumb-title" href="/korean-skin-treatments/upsell-kr">피부과에서 추가 시술을 권한다면, 어디까지 받아야 할까요?</Link><span aria-hidden="true">/</span><span aria-current="page">카드로 보기</span></nav>
<main className="cards-main"><div className="post-heading"><span className="post-mark" aria-hidden="true">읽</span><div><h1>피부과 가기 전, 알아둘 이야기</h1><p>추가 시술과 견적에 관한 상담 노트</p></div><span className="post-count" aria-hidden="true">10장</span></div>
<CardCarousel><section className="slide" role="group" aria-roledescription="슬라이드" aria-label="1 / 10"><div className="social-card cover-card"><div className="card-top"><span>피부과 가기 전</span><span>01 / 10</span></div><p className="cover-tag">상담실에서 당황하지 않으려면</p><h2>추가 시술,<br />꼭 받아야<br />할까요<span className="question-mark">?</span></h2><p className="cover-subtitle">업셀링과 필요한 권유,<br />그 차이를 알아두세요.</p><div className="card-bottom"><span>나를 위한 시술 선택 노트</span><span>넘겨보기 →</span></div></div></section>
<section className="slide" role="group" aria-roledescription="슬라이드" aria-label="2 / 10"><div className="social-card photo-card"><div className="card-top"><span>먼저, 용어부터</span><span>02 / 10</span></div><h2>‘업셀링’이<br />무슨 뜻일까요?</h2><p className="card-copy">원래 선택한 것보다 더 비싼 옵션이나<br />큰 용량을 구매하도록 권하는<br />판매 전략을 말해요.</p><figure className="card-photo"><Image src="/korean-skin-treatments/upsell-kr/consultation.webp" sizes="(max-width: 540px) calc(100vw - 80px), 410px" alt="시술 계획을 함께 살펴보는 상담 장면" width="1536" height="1024" /><figcaption>AI 제작 이미지</figcaption></figure><div className="card-bottom"><span>핵심은 나에게 필요한지</span><span>→</span></div></div></section>
<section className="slide" role="group" aria-roledescription="슬라이드" aria-label="3 / 10"><div className="social-card pink-card"><div className="card-top"><span>이런 상황이라면</span><span>03 / 10</span></div><h2>하나 받으러 갔는데,<br />권유는 여러 개?</h2><div className="scenario"><p><span>원래 목적</span><strong>리쥬란 상담</strong></p><div className="scenario-arrow" aria-hidden="true">↓</div><p><span>추가 권유</span><strong>써마지 · 울쎄라<br />토닝 10회</strong></p></div><p className="card-copy">함께 받지 않으면 안 될 것 같은 설명.<br /><strong>필요한 이유부터 확인하세요.</strong></p><div className="card-bottom"><span>원고에 인용된 개별 후기 요약</span><span>→</span></div></div></section>
<section className="slide" role="group" aria-roledescription="슬라이드" aria-label="4 / 10"><div className="social-card white-card"><div className="card-top"><span>말보다, 설명을 살펴보세요</span><span>04 / 10</span></div><h2>“같이 하면 좋아요.”<br />그다음 설명은?</h2><div className="speech-note muted-note"><span>막연한 설명</span><p>어디에, 어떻게 도움이 되는지<br />알기 어려워요.</p></div><div className="speech-note blue-note"><span>구체적인 설명</span><p>내 고민과의 관련성,<br />효과와 한계, 위험과 대안까지.</p></div><p className="card-copy compact">가능하다면 의사에게 확인하세요.</p><div className="card-bottom"><span>어려운 용어보다 구체적인 근거</span><span>→</span></div></div></section>
<section className="slide" role="group" aria-roledescription="슬라이드" aria-label="5 / 10"><div className="social-card lime-card"><div className="card-top"><span>가격을 비교할 때</span><span>05 / 10</span></div><h2>같은 시술,<br />다른 견적.</h2><p className="card-copy">이름이 같아도<br />조건까지 같은 것은 아니에요.</p><dl className="card-dl"><div><dt>용량</dt><dd>얼마나 사용하는지</dd></div><div><dt>범위</dt><dd>어느 부위까지 포함하는지</dd></div><div><dt>구성</dt><dd>1회인지, 패키지인지</dd></div></dl><div className="card-bottom"><span>가격 옆의 조건도 함께 비교</span><span>→</span></div></div></section>
<section className="slide" role="group" aria-roledescription="슬라이드" aria-label="6 / 10"><div className="social-card photo-card estimate-card"><div className="card-top"><span>방문하기 전에</span><span>06 / 10</span></div><h2>가견적은<br />구체적으로 물어보기.</h2><p className="card-copy">현재 피부 상태, 희망 시술과 부위를<br />자세히 알려주세요.<br /><strong>필요한 용량과 범위도 꼭 함께.</strong></p><figure className="card-photo"><Image src="/korean-skin-treatments/upsell-kr/estimate-comparison.webp" sizes="(max-width: 540px) calc(100vw - 80px), 410px" alt="견적서와 계산기가 놓인 책상" width="1536" height="1024" /><figcaption>AI 제작 이미지</figcaption></figure><div className="card-bottom"><span>최종 금액은 상태 확인 후 달라질 수 있어요</span><span>→</span></div></div></section>
<section className="slide" role="group" aria-roledescription="슬라이드" aria-label="7 / 10"><div className="social-card blue-card quote-card"><div className="card-top"><span>이렇게 말해도 괜찮아요</span><span>07 / 10</span></div><span className="large-quote" aria-hidden="true">“</span><h2>오늘은<br /><em>상담만</em><br />받을게요.</h2><p className="card-copy">상담일과 시술일을 따로 잡을 수 있는지<br />예약 전에 확인하세요.<br />생각할 시간도 필요한 과정이에요.</p><div className="card-bottom"><span>결정을 서두르지 않기</span><span>→</span></div></div></section>
<section className="slide" role="group" aria-roledescription="슬라이드" aria-label="8 / 10"><div className="social-card white-card package-card"><div className="card-top"><span>패키지를 권유받았다면</span><span>08 / 10</span></div><p className="big-number">10<span>회</span></p><h2>할인율보다 먼저,<br />내가 쓸 수 있는 횟수.</h2><p className="card-copy">한국에 자주 오기 어렵다면<br />실제로 이용할 수 있을지 생각해 보세요.</p><div className="underline-note">필요한 횟수 · 방문 일정 · 총 결제 금액</div><div className="card-bottom"><span>많이 산다고 항상 합리적이지는 않아요</span><span>→</span></div></div></section>
<section className="slide" role="group" aria-roledescription="슬라이드" aria-label="9 / 10"><div className="social-card pink-card"><div className="card-top"><span>상담 일정을 정할 때</span><span>09 / 10</span></div><h2>2~3곳을 비교하고,<br />결정은 그다음에.</h2><ol className="card-steps"><li><span>1</span><div><strong>상담 먼저 예약하기</strong><p>시술과 분리할 수 있는지 확인</p></div></li><li><span>2</span><div><strong>설명과 견적 정리하기</strong><p>내 고민 · 효과 · 용량 · 범위</p></div></li><li><span>3</span><div><strong>비교한 뒤 시술 예약하기</strong><p>납득한 내용으로 선택</p></div></li></ol><div className="card-bottom"><span>일정 분리가 어렵다면 가견적부터 비교</span><span>→</span></div></div></section>
<section className="slide" role="group" aria-roledescription="슬라이드" aria-label="10 / 10"><div className="social-card closing-card"><div className="card-top"><span>결제 전에 다시 확인</span><span>10 / 10</span></div><h2>내 피부의 선택은,<br /><em>내가 납득한 뒤에.</em></h2><ul className="card-checks"><li>나에게 필요한 이유를 들었나요?</li><li>효과와 한계, 위험을 확인했나요?</li><li>용량과 범위, 금액을 비교했나요?</li><li>생각할 시간을 충분히 가졌나요?</li></ul><p className="last-line">질문은 충분히.<br />결정은 내 속도로.</p><div className="card-bottom"><span>상담 전, 한 번 더 읽어두세요.</span><span>✓</span></div></div></section></CardCarousel>
<div className="post-caption"><p><strong>추가 시술을 권유받았을 때, 꼭 기억할 것.</strong><br />원하지 않는다면 거절해도 괜찮아요.<br />필요한 이유를 듣고, 견적을 비교한 뒤 결정하세요.</p><Link prefetch={false} href="/korean-skin-treatments/upsell-kr">사례와 자세한 설명은 글로 읽기 →</Link><p className="caption-tags">#피부과상담 #업셀링 #시술견적 #한국피부과</p><p className="caption-note">시술 선택을 위한 일반적인 정보입니다. 개인에게 적합한 시술은 의사와 상담하세요. 사진은 AI로 제작한 예시 이미지입니다.</p></div>
</main><footer className="relyn-footer"><div><Link prefetch={false} className="footer-wordmark" href="/">RELYN</Link><p>주식회사 렐린 · 대표이사 장기석 · 사업자등록번호 299-03-03608</p></div><nav aria-label="RELYN 안내"><Link prefetch={false} href="/korean-skin-treatments/upsell-jp/cards" hrefLang="ja-JP" lang="ja">日本語</Link><Link prefetch={false} href="/korean-skin-treatments/upsell-tw/cards" hrefLang="zh-TW" lang="zh-TW">繁體中文</Link><Link prefetch={false} href="/">RELYN 소개 ↗</Link><Link prefetch={false} href="/privacy">개인정보처리방침</Link></nav></footer>
    <ArticleFeedback />
  </div>;
}
