// Generated by scripts/optimize-skin-guide-images.cjs. Do not edit by hand.
export const guideImages: Record<string, { width: number; height: number; variants: { src: string; width: number }[] }> = {
  "/korean-skin-treatments/review-guide-kr/review-scout.png": {
    "width": 1149,
    "height": 1369,
    "variants": [
      {
        "src": "/korean-skin-treatments/optimized/review-scout-384-c55900ed26.webp",
        "width": 384
      },
      {
        "src": "/korean-skin-treatments/optimized/review-scout-768-554010312a.webp",
        "width": 768
      },
      {
        "src": "/korean-skin-treatments/optimized/review-scout-1149-1f0ae569eb.webp",
        "width": 1149
      }
    ]
  },
  "/korean-skin-treatments/review-guide-kr/review-scout-photo.png": {
    "width": 1254,
    "height": 1254,
    "variants": [
      {
        "src": "/korean-skin-treatments/optimized/review-scout-photo-384-855265d030.webp",
        "width": 384
      },
      {
        "src": "/korean-skin-treatments/optimized/review-scout-photo-768-abdec592ef.webp",
        "width": 768
      },
      {
        "src": "/korean-skin-treatments/optimized/review-scout-photo-1152-54e7e30fd7.webp",
        "width": 1152
      },
      {
        "src": "/korean-skin-treatments/optimized/review-scout-photo-1254-c4aa4e95dd.webp",
        "width": 1254
      }
    ]
  },
  "/korean-skin-treatments/review-guide-kr/review-consultation.png": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "src": "/korean-skin-treatments/optimized/review-consultation-384-a4ba661cce.webp",
        "width": 384
      },
      {
        "src": "/korean-skin-treatments/optimized/review-consultation-768-8d9fe4817a.webp",
        "width": 768
      },
      {
        "src": "/korean-skin-treatments/optimized/review-consultation-1152-1cbac98c57.webp",
        "width": 1152
      },
      {
        "src": "/korean-skin-treatments/optimized/review-consultation-1536-109092d8f2.webp",
        "width": 1536
      }
    ]
  },
  "/korean-skin-treatments/review-guide-kr/review-content-studio.png": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "src": "/korean-skin-treatments/optimized/review-content-studio-384-3747325dea.webp",
        "width": 384
      },
      {
        "src": "/korean-skin-treatments/optimized/review-content-studio-768-5c694ad2b3.webp",
        "width": 768
      },
      {
        "src": "/korean-skin-treatments/optimized/review-content-studio-1152-5a0e21305d.webp",
        "width": 1152
      },
      {
        "src": "/korean-skin-treatments/optimized/review-content-studio-1536-7698a5640e.webp",
        "width": 1536
      }
    ]
  },
  "/korean-skin-treatments/review-guide-kr/review-compare.png": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "src": "/korean-skin-treatments/optimized/review-compare-384-4f7a62d6e0.webp",
        "width": 384
      },
      {
        "src": "/korean-skin-treatments/optimized/review-compare-768-d1b27930c6.webp",
        "width": 768
      },
      {
        "src": "/korean-skin-treatments/optimized/review-compare-1152-b7faeed4ef.webp",
        "width": 1152
      },
      {
        "src": "/korean-skin-treatments/optimized/review-compare-1536-3f6919e7b8.webp",
        "width": 1536
      }
    ]
  },
  "/korean-skin-treatments/review-guide-kr/review-creator.png": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "src": "/korean-skin-treatments/optimized/review-creator-384-0d1bba2866.webp",
        "width": 384
      },
      {
        "src": "/korean-skin-treatments/optimized/review-creator-768-5217f03e6b.webp",
        "width": 768
      },
      {
        "src": "/korean-skin-treatments/optimized/review-creator-1152-b9e9960e85.webp",
        "width": 1152
      },
      {
        "src": "/korean-skin-treatments/optimized/review-creator-1536-6cb9c08541.webp",
        "width": 1536
      }
    ]
  },
  "/korean-skin-treatments/review-guide-kr/review-questions.png": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "src": "/korean-skin-treatments/optimized/review-questions-384-08e580a630.webp",
        "width": 384
      },
      {
        "src": "/korean-skin-treatments/optimized/review-questions-768-ef8eca5622.webp",
        "width": 768
      },
      {
        "src": "/korean-skin-treatments/optimized/review-questions-1152-a98734cc5e.webp",
        "width": 1152
      },
      {
        "src": "/korean-skin-treatments/optimized/review-questions-1536-15c406ac17.webp",
        "width": 1536
      }
    ]
  },
  "/korean-skin-treatments/upsell-kr/consultation.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "src": "/korean-skin-treatments/optimized/consultation-384-0933dc4540.webp",
        "width": 384
      },
      {
        "src": "/korean-skin-treatments/optimized/consultation-768-a5ab11d588.webp",
        "width": 768
      },
      {
        "src": "/korean-skin-treatments/optimized/consultation-1152-79efea043d.webp",
        "width": 1152
      },
      {
        "src": "/korean-skin-treatments/optimized/consultation-1536-55f88d6f56.webp",
        "width": 1536
      }
    ]
  },
  "/korean-skin-treatments/upsell-kr/estimate-comparison.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "src": "/korean-skin-treatments/optimized/estimate-comparison-384-89cb0ef47e.webp",
        "width": 384
      },
      {
        "src": "/korean-skin-treatments/optimized/estimate-comparison-768-964f81f337.webp",
        "width": 768
      },
      {
        "src": "/korean-skin-treatments/optimized/estimate-comparison-1152-2d3350b699.webp",
        "width": 1152
      },
      {
        "src": "/korean-skin-treatments/optimized/estimate-comparison-1536-210073a36d.webp",
        "width": 1536
      }
    ]
  },
  "/relyn_logo.png": {
    "width": 1024,
    "height": 358,
    "variants": [
      {
        "src": "/korean-skin-treatments/optimized/relyn_logo-128-c6694b1081.webp",
        "width": 128
      },
      {
        "src": "/korean-skin-treatments/optimized/relyn_logo-256-eab8e2a060.webp",
        "width": 256
      },
      {
        "src": "/korean-skin-treatments/optimized/relyn_logo-384-3d02578a3d.webp",
        "width": 384
      }
    ]
  }
};
